# Generated by Django 2.2.3 on 2019-10-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dict_mod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=30)),
                ('caption', models.CharField(max_length=100)),
            ],
        ),
    ]
