# Generated by Django 2.2.3 on 2019-10-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_dict_mod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tb_car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnum', models.CharField(max_length=500)),
                ('carattr', models.CharField(max_length=500)),
                ('carsize', models.CharField(max_length=500)),
                ('begin1', models.DateTimeField()),
                ('end1', models.DateTimeField()),
                ('begin2', models.DateTimeField()),
                ('end2', models.DateTimeField()),
                ('inrecid', models.CharField(max_length=500)),
                ('outrecid', models.CharField(max_length=500)),
                ('intime', models.DateTimeField()),
                ('outime', models.DateTimeField()),
                ('tpriceid', models.CharField(max_length=500)),
                ('expired1', models.CharField(max_length=500)),
                ('expired2', models.CharField(max_length=500)),
            ],
        ),
    ]
